config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  
  resources :restaurants do
    resources :items do
      resources :orders
    end
  end

  resources :orders
  
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  # get "/auth/facebook/callback", to: "omniauth_callbacks#facebook"
  
  # devise_for :users

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :items
    has_many :orders
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if
      @restaurant.save
      redirect_to restaurants_path
    else
      render action = 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/index.html.erb
<h3>Restaurants
<%= link_to 'New restaurant', new_restaurant_path %></h3>
<table>
    <% @restaurants.each do |restaurant| %>
        <tr>
            <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>  
            <td><%#= link_to 'Show', restaurant_path(restaurant) %></td>  
        </tr>
    <% end %>
</table>

app/views/restaurants/new.html.erb
  <%= form_with scope: :restaurant, url: restaurants_path, local: true do |form| %>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </p>
    
    <p>
        <%= form.label :address %><br>
        <%= form.text_area :address %>
    </p>

    <p>
        <%= form.label :phone_number %><br>
        <%= form.text_area :phone_number %>
    </p>
    
    <p>
        <%= form.submit %>
    </p>
    <% end %>

app/views/restaurants/show.html.erb
<p>
    <strong><%= @restaurant.name %></strong>, <%= @restaurant.address %>
</p>


<p>
    <%= @restaurant.phone_number %>
</p>


<h3>Items
<%= link_to  "New item",  new_restaurant_item_path(@restaurant) %></h3>

<table>
    <% @restaurant.items.each do |item| %>
        <tr>
            <td><%= item.name %></td> 
            <td><%= item.price %></td> 
            <td><%= link_to 'Show', restaurant_item_path(@restaurant, item)  %></td> 
            <td><%= link_to "Add-to-order", new_order_path %></td>

        </tr>
    <% end %>
</table>